QuizCore.createGame([
        {"en": "As far as I know", "pt": "Até onde eu sei"},
        {"en": "In my opinion", "pt": "Na minha opinião"},
        {"en": "I see", "pt": "Entendi"},
        {"en": "It depends", "pt": "Depende"},
        {"en": "I don't mind", "pt": "Não me importo"},
        {"en": "I couldn't agree more", "pt": "Não poderia concordar mais"},
        {"en": "That makes sense", "pt": "Faz sentido"},
        {"en": "No wonder", "pt": "Não é à toa"},
        {"en": "Did you answer the phone?", "pt": "Você atendeu o telefone?"},
        {"en": "I can't wait", "pt": "Mal posso esperar"},
        {"en": "I don't care", "pt": "Não ligo"},
        {"en": "He never makes prank calls", "pt": "Ele nunca passa trotes"},
        {"en": "I take a nap after lunch", "pt": "Eu tiro um cochilo depois do almoço"},
        {"en": "I was always in trouble", "pt": "Eu sempre estava em encrenca"},
        {"en": "Can I take your order?", "pt": "Posso anotar seu pedido?"},
        {"en": "A little bit", "pt": "Um pouco"},
        {"en": "I'm full", "pt": "Estou satisfeito"},
        {"en": "Take your time", "pt": "Leve o tempo que precisar"},
        {"en": "Can I have the check, please?", "pt": "A conta, por favor"},
        {"en": "How about some noodles?", "pt": "Que tal um pouco de macarrão?"},
        {"en": "Did she book the hotel?", "pt": "Ela reservou o hotel?"},
        {"en": "I always make my bed", "pt": "Eu sempre arrumo a cama"},
        {"en": "By mistake", "pt": "Por engano"},
        {"en": "When I grow up", "pt": "Quando eu crescer"},
        {"en": "What is it made of?", "pt": "Do que é feito?"},
        {"en": "I found out", "pt": "Eu descobri"},
        {"en": "My father is running for mayor", "pt": "Meu pai é candidato a prefeito"},
        {"en": "Put on your coat", "pt": "Coloque seu casaco"},
        {"en": "Where did you get a suntan?", "pt": "Onde você pegou o bronzeado?"},
        {"en": "Get sunburned", "pt": "Ficar com queimadura de sol"},
        {"en": "Every other day", "pt": "Dia sim, dia não"},
        {"en": "I'm broke", "pt": "Estou sem dinheiro"},
        {"en": "To be honest", "pt": "Para ser honesto"},
        {"en": "By the way", "pt": "A propósito"},
        {"en": "After all", "pt": "Afinal"},
        {"en": "For example", "pt": "Por exemplo"},
        {"en": "At least", "pt": "Pelo menos"},
        {"en": "You're grounded", "pt": "Você está de castigo"},
        {"en": "In fact", "pt": "Na verdade"},
        {"en": "As usual", "pt": "Como sempre"},
        {"en": "Once in a while", "pt": "De vez em quando"},
        {"en": "Sooner or later", "pt": "Mais cedo ou mais tarde"},
        {"en": "From now on", "pt": "De agora em diante"},
        {"en": "So far", "pt": "Até agora"},
        {"en": "In the end", "pt": "No final"},
        {"en": "On time", "pt": "Na hora"},
        {"en": "In time", "pt": "A tempo"},
        {"en": "Right away", "pt": "Imediatamente"},
        {"en": "I'm starving! What's for dinner?", "pt": "Estou com fome! O que tem para jantar?"},
        {"en": "No longer", "pt": "Não mais"},
        {"en": "Once again", "pt": "Mais uma vez"},
        {"en": "Have a nice trip!", "pt": "Boa viagem!"},
        {"en": "At first", "pt": "No começo"},
        {"en": "For now", "pt": "Por enquanto"},
        {"en": "Even though", "pt": "Mesmo que"},
        {"en": "As soon as possible", "pt": "O mais rápido possível"},
        {"en": "It's up to you", "pt": "Depende de você"},
        {"en": "Keep in touch", "pt": "Mantenha contato"},
        {"en": "Long story short", "pt": "Resumindo"},
        {"en": "It's up to me", "pt": "Depende de mim"},
        {"en": "Never give up", "pt": "Nunca desista"},
        {"en": "A piece of advice", "pt": "Um conselho"},
        {"en": "I appreciate it", "pt": "Eu agradeço"},
        {"en": "Sounds good", "pt": "Parece ótimo"},
        {"en": "That sounds great", "pt": "Parece ótimo"},
        {"en": "I'm looking forward to it", "pt": "Estou ansioso por isso"},
        {"en": "It doesn't matter", "pt": "Não importa"},
        {"en": "It's worth it", "pt": "Vale a pena"},
        {"en": "I'm not in a hurry", "pt": "Eu não estou com pressa"},
        {"en": "Trust me", "pt": "Confie em mim"},
        {"en": "That's enough", "pt": "Chega"},
        {"en": "Don't mention it", "pt": "Não há de quê"},
        {"en": "Take a seat", "pt": "Sente-se"},
        {"en": "Would you like some coffee?", "pt": "Você gostaria de um pouco de café?"},
        {"en": "Feel free", "pt": "Fique à vontade"},
        {"en": "Help yourself", "pt": "Sirva-se"},
        {"en": "It's my pleasure", "pt": "Foi um prazer"},
        {"en": "I'm on my way", "pt": "Estou a caminho"},
        {"en": "I'm looking for the bus station", "pt": "Estou procurando a rodoviária"},
        {"en": "Give me a hand", "pt": "Me dê uma mão"},
        {"en": "Hang on", "pt": "Espere um momento"},
        {"en": "Hold on", "pt": "Espere um instante"},
        {"en": "What's going on?", "pt": "O que está acontecendo?"},
        {"en": "How come?", "pt": "Como assim?"},
        {"en": "You never know", "pt": "Nunca se sabe"},
        {"en": "That's true", "pt": "É verdade"},
        {"en": "I mean", "pt": "Quero dizer"},
        {"en": "Just in case", "pt": "Por via das dúvidas"},
        {"en": "For sure", "pt": "Com certeza"},
        {"en": "Without a doubt", "pt": "Sem dúvida"},
        {"en": "What do you mean?", "pt": "O que você quer dizer?"},
        {"en": "Can you explain?", "pt": "Você pode explicar?"},
        {"en": "That's interesting", "pt": "Isso é interessante"},
        {"en": "I wasn't expecting that", "pt": "Eu não esperava isso"},
        {"en": "It couldn't be better", "pt": "Não poderia estar melhor"},
        {"en": "Everything worked out", "pt": "Tudo deu certo"},
        {"en": "What a coincidence!", "pt": "Que coincidência!"},
        {"en": "Could you say that again?", "pt": "Você pode repetir isso?"},
        {"en": "I hope everything goes well", "pt": "Espero que tudo corra bem"},
        {"en": "What are you waiting for?", "pt": "O que você está esperando?"}]);