QuizCore.createGame([
        {"en": "Important", "pt": "Importante"}, 
        {"en": "Delicious", "pt": "Delicioso"}, 
        {"en": "Comfortable", "pt": "Confortável"}, 
        {"en": "Interesting", "pt": "Interessante"},
        {"en": "Front desk", "pt": "Recepção"},
        {"en": "Manager", "pt": "Gerente"},
        {"en": "Reservation", "pt": "Reserva"},
        {"en": "Housekeeper", "pt": "Camareiro(a)"},
        {"en": "Single bed", "pt": "Cama de solteiro"},
        {"en": "Double bed", "pt": "Cama de casal"},
        {"en": "Pillow", "pt": "Travesseiro"},
        {"en": "Blanket", "pt": "Cobertor"},
        {"en": "Mattress", "pt": "Colchão"},
        {"en": "Alarm clock", "pt": "Despertador"},
        {"en": "Candle", "pt": "Vela"},
        {"en": "Somebody", "pt": "Alguém"},
        {"en": "Anybody", "pt": "Alguém, ninguém"},
        {"en": "Nobody", "pt": "Ninguém"},
        {"en": "Everybody", "pt": "Todo mundo"},
        {"en": "Something", "pt": "Alguma coisa"},
        {"en": "Anything", "pt": "Qualquer coisa"},
        {"en": "Nothing", "pt": "Nada"},
        {"en": "Without", "pt": "Sem"},
        {"en": "French fries", "pt": "Batatas fritas"},
        {"en": "Hamburger", "pt": "Hambúrguer"},
        {"en": "Hot dog", "pt": "Cachorro-quente"},
        {"en": "Mayonnaise", "pt": "Maionese"},
        {"en": "Mustard", "pt": "Mostarda"},
        {"en": "Dish", "pt": "Prato"},
        {"en": "Pepper", "pt": "Pimenta"},
        {"en": "Salt", "pt": "Sal"},
        {"en": "Spice", "pt": "Tempero"},
        {"en": "Tasty", "pt": "Saboroso"},
        {"en": "Rare", "pt": "Mal passado"},
        {"en": "Medium", "pt": "Ao ponto"},
        {"en": "Well done", "pt": "Bem passado"},
        {"en": "Document", "pt": "Documento"},
        {"en": "Weight", "pt": "Peso"},
        {"en": "Height", "pt": "Altura"},
        {"en": "ID", "pt": "Documento de identidade"},
        {"en": "Passport", "pt": "Passaporte"},
        {"en": "Single", "pt": "Solteiro(a)"},
        {"en": "Married", "pt": "Casado(a)"},
        {"en": "Widower", "pt": "Viúvo"},
        {"en": "Widow", "pt": "Viúva"},
        {"en": "Divorced", "pt": "Divorciado(a)"},
        {"en": "Child", "pt": "Criança"},
        {"en": "Childhood", "pt": "Infância"},
        {"en": "Memory", "pt": "Memória"},
        {"en": "Adult", "pt": "Adulto(a)"},
        {"en": "Hero", "pt": "Herói"},
        {"en": "Character", "pt": "Personagem"},
        {"en": "Pastime", "pt": "Passatempo"},
        {"en": "Activity", "pt": "Atividade"},
        {"en": "Toy", "pt": "Brinquedo"},
        {"en": "Doll", "pt": "Boneca"},
        {"en": "Dream", "pt": "Sonho"},
        {"en": "Still", "pt": "Ainda"},
        {"en": "Diary", "pt": "Diário"},
        {"en": "Calendar", "pt": "Calendário"},
        {"en": "Roommate", "pt": "Colega de quarto"},
        {"en": "Rule", "pt": "Regra"},
        {"en": "Amazing", "pt": "Incrível"},
        {"en": "Careful", "pt": "Cuidadoso"},
        {"en": "Embarrassed", "pt": "Envergonhado"},
        {"en": "Wonderful", "pt": "Maravilhoso"},
        {"en": "Excited", "pt": "Empolgado, entusiasmado"},
        {"en": "Career", "pt": "Carreira"},
        {"en": "Meeting", "pt": "Reunião"},
        {"en": "Public", "pt": "Público(a)"},
        {"en": "Private", "pt": "Particular"},
        {"en": "Elementary school", "pt": "Ensino fundamental"},
        {"en": "High school", "pt": "Ensino Médio"},
        {"en": "College", "pt": "Faculdade"},
        {"en": "University", "pt": "Universidade"},
        {"en": "Wool", "pt": "Lã"},
        {"en": "Wood", "pt": "Madeira"},
        {"en": "Iron", "pt": "Ferro"},
        {"en": "Thread", "pt": "Linha"},
        {"en": "Glue", "pt": "Cola"},
        {"en": "Ruler", "pt": "Régua"},
        {"en": "Scissors", "pt": "Tesoura"},
        {"en": "Half", "pt": "Meio, metade"},
        {"en": "Shape", "pt": "Forma, formato"},
        {"en": "Round", "pt": "Redondo"},
        {"en": "Square", "pt": "Quadrado"},
        {"en": "Triangular", "pt": "Triangular"},
        {"en": "While", "pt": "Enquanto"},
        {"en": "Fortunately", "pt": "Felizmente"},
        {"en": "Unfortunately", "pt": "Infelizmente"},
        {"en": "Immediately", "pt": "Imediatamente"},
        {"en": "Lie", "pt": "Mentira"},
        {"en": "Truth", "pt": "Verdade"},
        {"en": "Opinion", "pt": "Opinião"},
        {"en": "Danger", "pt": "Perigo"},
        {"en": "Seat", "pt": "Assento"},
        {"en": "Map", "pt": "Mapa"},
        {"en": "Pilot", "pt": "Piloto"},
        {"en": "Almost", "pt": "Quase"},
        {"en": "Life", "pt": "Vida"}]);