QuizCore.createGame([
  { en: "Hello", pt: "Olá" },
  { en: "Good morning", pt: "Bom dia" },
  { en: "Good afternoon", pt: "Boa tarde" },
  { en: "Good evening", pt: "Boa noite" },
  { en: "Nice to meet you", pt: "Prazer em conhecer você" },
  { en: "Please", pt: "Por favor" },
  { en: "Thank you", pt: "Obrigado" },
  { en: "You're welcome", pt: "De nada" },
  { en: "Excuse me", pt: "Com licença" },
  { en: "I'm sorry", pt: "Desculpa" },
  { en: "Maybe", pt: "Talvez" },
  { en: "What's your name?", pt: "Qual é o seu nome?" },
  { en: "How do you spell your name?", pt: "Como você escreve o seu nome?" },
  { en: "Where are you from?", pt: "De onde você é?" },
  { en: "What time is it?", pt: "Que horas são?" },
  { en: "I don't understand", pt: "Não entendo" },
  { en: "I don't know", pt: "Não sei" },
  { en: "A piece of cake", pt: "Isso é muito fácil" },
  { en: "It's okay", pt: "Tudo bem" },
  { en: "I'm fine, thank you", pt: "Estou bem, obrigado" },
  { en: "I'm tired", pt: "Estou cansado" },
  { en: "I'm hungry", pt: "Estou com fome" },
  { en: "I'm thirsty", pt: "Estou com sede" },
  { en: "I'm bored", pt: "Estou entediado" },
  { en: "Welcome to the park", pt: "Bem-vindo ao parque" },
  { en: "See you later", pt: "Até mais" }
]);
