QuizCore.createGame([
  { en: "Hello", pt: "Olá" },
  { en: "Good morning", pt: "Bom dia" },
  { en: "Good afternoon", pt: "Boa tarde" },
  { en: "Good evening", pt: "Boa noite" },
  { en: "Nice to meet you", pt: "Prazer em conhecer você" },
  { en: "Please", pt: "Por favor" },
  { en: "Thank you", pt: "Obrigado" },
  { en: "You're welcome", pt: "De nada" },
  { en: "Excuse me", pt: "Com licença" },
  { en: "I'm sorry", pt: "Desculpa" },
  { en: "Maybe", pt: "Talvez" },
  { en: "What's your name?", pt: "Qual é o seu nome?" },
  { en: "How do you spell your name?", pt: "Como você escreve o seu nome?" },
  { en: "Where are you from?", pt: "De onde você é?" },
  { en: "What time is it?", pt: "Que horas são?" },
  { en: "I don't understand", pt: "Não entendo" },
  { en: "I don't know", pt: "Não sei" },
  { en: "A piece of cake", pt: "Isso é muito fácil" },
  { en: "It's okay", pt: "Tudo bem" },
  { en: "I'm fine, thank you", pt: "Estou bem, obrigado" },
  { en: "I'm tired", pt: "Estou cansado" },
  { en: "I'm hungry", pt: "Estou com fome" },
  { en: "I'm thirsty", pt: "Estou com sede" },
  { en: "I'm bored", pt: "Estou entediado" },
  { en: "See you later", pt: "Até mais" },
  { en: "Goodbye", pt: "Adeus" },
  { en: "Take care", pt: "Se cuida" },
  { en: "What about you?", pt: "E você?" },
  { en: "I have breakfast", pt: "Eu tomo café da manhã" },
  { en: "You study here, right?", pt: "Você estuda aqui, certo?" },
  { en: "It's two o'clock", pt: "São duas horas" },
  { en: "I eat a lot of fruit", pt: "Eu como muita fruta" },
  { en: "How often", pt: "Com que frequência" },
  { en: "That's right", pt: "Isso mesmo" },
  { en: "I'm sure", pt: "Tenho certeza" },
  { en: "Let's hang out", pt: "Vamos dar uma volta" },
  { en: "What's wrong?", pt: "Qual o problema?" },
  { en: "Take it easy", pt: "Fique tranquilo" },
  { en: "I do sit-ups", pt: "Eu faço abdominais" },
  { en: "Can you do push-ups?", pt: "Você consegue fazer flexões?" },
  { en: "Let's jump rope", pt: "Vamos pular corda" },
  { en: "I work out at the gym", pt: "Eu malho na academia" },
  { en: "Do the dishes", pt: "Lave os pratos" },
  { en: "Set the table", pt: "Arrume a mesa" },
  { en: "I'm cleaning up", pt: "Estou limpando" },
  { en: "Do not litter", pt: "Não jogue lixo no chão" },
  { en: "No fishing", pt: "Proibido pescar" },
  { en: "It's sunny", pt: "Está ensolarado" },
  { en: "It's cloudy", pt: "Está nublado" },
  { en: "It's rainy", pt: "Está chovoso" },
  { en: "It's snowing", pt: "Está nevando" },
  { en: "Take a look", pt: "Dê uma olhada" },
  { en: "Looks like", pt: "Parece" },
  { en: "What kind of movie?", pt: "Qual tipo de filme?" },
  { en: "Too bad", pt: "Que pena" },
  { en: "Thanks a lot", pt: "Muito obrigado" },
  { en: "Let's have a barbecue", pt: "Vamos fazer um churrasco" },
  { en: "What a mess!", pt: "Que bagunça!" },
  { en: "I'm joking", pt: "Estou brincando" },
  { en: "Can you fly a kite?", pt: "Você sabe empinar pipa?" },
  { en: "Watch out!", pt: "Cuidado!" },
  { en: "Free time", pt: "Tempo livre" },
  { en: "Travel abroad", pt: "Viajar ao exterior" },
  { en: "I don't get it", pt: "Não entendo" },
  { en: "How are you?", pt: "Como você está?" },
  { en: "Have a nice day", pt: "Tenha um bom dia" },
  { en: "Good luck!", pt: "Boa sorte!" },
  { en: "Congratulations!", pt: "Parabéns!" },
  { en: "Happy birthday!", pt: "Feliz aniversário!" },
  { en: "Bless you!", pt: "Saúde!" },
  { en: "Of course", pt: "Claro" },
  { en: "No problem", pt: "Sem problemas" },
  { en: "I agree", pt: "Eu concordo" },
  { en: "Never mind", pt: "Deixa pra lá" },
  { en: "Don't worry", pt: "Não se preocupe" },
  { en: "Be careful", pt: "Tenha cuidado" },
  { en: "Come here", pt: "Venha aqui" },
  { en: "Go ahead", pt: "Pode continuar" },
  { en: "Wait a minute", pt: "Espere um minuto" },
  { en: "Just a moment", pt: "Só um momento" },
  { en: "Can I help you?", pt: "Posso ajudar?" },
  { en: "How much is it?", pt: "Quanto custa?" },
  { en: "I'm in a hurry", pt: "Estou com pressa" },
  { en: "That's awesome!", pt: "Isso é incrível!" },
  { en: "I think so", pt: "Acho que sim" },
  { en: "I hope so", pt: "Espero que sim" },
  { en: "I miss you", pt: "Sinto sua falta" },
  { en: "Long time no see", pt: "Quanto tempo!" },
  { en: "See you soon", pt: "Até logo" },
  { en: "Come on!", pt: "Vamos!" },
  { en: "Be quiet", pt: "Fique quieto" },
  { en: "Have fun!", pt: "Divirta-se!" },
  { en: "Take your time", pt: "Sem pressa" },
  { en: "What happened?", pt: "O que aconteceu?" },
  { en: "That's enough", pt: "Chega" },
  { en: "I'm lost", pt: "Estou perdido" },
  { en: "Can you repeat that?", pt: "Pode repetir?" },
  { en: "Speak slowly, please", pt: "Fale devagar, por favor" },
  { en: "I need help", pt: "Preciso de ajuda" },
  { en: "Have a good weekend", pt: "Tenha um bom fim de semana" }
]);

