QuizCore.createGame([
  { en: "House", pt: "Casa" },
  { en: "Car", pt: "Carro" },
  { en: "Book", pt: "Livro" },
  { en: "Water", pt: "Água" },
  { en: "Food", pt: "Comida" },
  { en: "Friend", pt: "Amigo" },
  { en: "Family", pt: "Família" },
  { en: "School", pt: "Escola" },
  { en: "Work", pt: "Trabalho" },
  { en: "Money", pt: "Dinheiro" },
  { en: "Big", pt: "Grande" },
  { en: "Small", pt: "Pequeno" },
  { en: "Good", pt: "Bom" },
  { en: "Bad", pt: "Ruim" },
  { en: "Hot", pt: "Quente" },
  { en: "Late", pt: "Tarde" },
  { en: "Early", pt: "Cedo" },
  { en: "Here", pt: "Aqui" },
  { en: "There", pt: "Lá" },
  { en: "Now", pt: "Agora" },
  { en: "Then", pt: "Então" },
  { en: "Today", pt: "Hoje" },
  { en: "Tomorrow", pt: "Amanhã" },
  { en: "Yesterday", pt: "Ontem" },
  { en: "Book", pt: "Livro" },
  { en: "Cold", pt: "Frio" }
]);
