QuizCore.createGame([
  { en: "House", pt: "Casa" },
  { en: "Car", pt: "Carro" },
  { en: "Book", pt: "Livro" },
  { en: "Water", pt: "Água" },
  { en: "Food", pt: "Comida" },
  { en: "Friend", pt: "Amigo" },
  { en: "Family", pt: "Família" },
  { en: "School", pt: "Escola" },
  { en: "Work", pt: "Trabalho" },
  { en: "Money", pt: "Dinheiro" },
  { en: "Big", pt: "Grande" },
  { en: "Small", pt: "Pequeno" },
  { en: "Good", pt: "Bom" },
  { en: "Bad", pt: "Ruim" },
  { en: "Hot", pt: "Quente" },
  { en: "Late", pt: "Tarde" },
  { en: "Early", pt: "Cedo" },
  { en: "Here", pt: "Aqui" },
  { en: "There", pt: "Lá" },
  { en: "Now", pt: "Agora" },
  { en: "Then", pt: "Então" },
  { en: "Today", pt: "Hoje" },
  { en: "Tomorrow", pt: "Amanhã" },
  { en: "Yesterday", pt: "Ontem" },
  { en: "Mall", pt: "Shopping" },
  { en: "Movie", pt: "Filme" },
  { en: "Restaurant", pt: "Restaurante" },
  { en: "Grocery store", pt: "Supermercado, mercearia" },
  { en: "Park", pt: "Parque" },
  { en: "Ice cream parlor", pt: "Sorveteria" },
  { en: "Month", pt: "Mês" },
  { en: "Year", pt: "Ano" },
  { en: "Father", pt: "Pai" },
  { en: "Mother", pt: "Mãe" },
  { en: "Parents", pt: "Pais" },
  { en: "Brother", pt: "Irmão" },
  { en: "Sister", pt: "Irmã" },
  { en: "Sibling", pt: "Irmão, irmã" },
  { en: "Classmate", pt: "Colega de classe" },
  { en: "Teacher", pt: "Professor" },
  { en: "Student", pt: "Estudante" },
  { en: "English", pt: "Inglês" },
  { en: "French", pt: "Francês" },
  { en: "Spanish", pt: "Espanhol" },
  { en: "Portuguese", pt: "Português" },
  { en: "German", pt: "Alemão" },
  { en: "I", pt: "Eu" },
  { en: "You", pt: "Você" },
  { en: "He", pt: "Ele" },
  { en: "She", pt: "Ela" },
  { en: "We", pt: "Nós" },
  { en: "They", pt: "Eles/Elas" },
  { en: "It", pt: "Ele, ela (objetos ou animais)" },
  { en: "My", pt: "Meu, Minha" },
  { en: "Your", pt: "Seu, Sua" },
  { en: "His", pt: "Dele" },
  { en: "Her", pt: "Dela" },
  { en: "Our", pt: "Nosso, nossa" },
  { en: "Their", pt: "Deles, delas" },
  { en: "And", pt: "E" },
  { en: "But", pt: "Mas" },
  { en: "Or", pt: "Ou" },
  { en: "Because", pt: "Porque" },
  { en: "With", pt: "Com" },
  { en: "Bread", pt: "Pão" },
  { en: "Milk", pt: "Leite" },
  { en: "Cheese", pt: "Queijo" },
  { en: "Eggs", pt: "Ovos" },
  { en: "Pancake", pt: "Panqueca" },
  { en: "Juice", pt: "Suco" },
  { en: "Coffee", pt: "Café" },
  { en: "Tea", pt: "Chá" },
  { en: "Butter", pt: "Manteiga" },
  { en: "Jam", pt: "Geleia caseira" },
  { en: "Jelly", pt: "Geleia" },
  { en: "Salad", pt: "Salada" },
  { en: "Soup", pt: "Sopa" },
  { en: "Pie", pt: "Torta" },
  { en: "Dessert", pt: "Sobremesa" },
  { en: "Slice", pt: "Fatia" },
  { en: "Pasta", pt: "Massa" },
  { en: "Sandwich", pt: "Sanduíche" },
  { en: "Cake", pt: "Bolo" },
  { en: "Cookie", pt: "Biscoito" },
  { en: "Ice cream", pt: "Sorvete" },
  { en: "Beer", pt: "Cerveja" },
  { en: "Wine", pt: "Vinho" },
  { en: "Lunch", pt: "Almoço" },
  { en: "Dinner", pt: "Jantar" },
  { en: "Breakfast", pt: "Café da manhã" },
  { en: "Snack", pt: "Lanche" },
  { en: "Fast food", pt: "Comida rápida" },
  { en: "Healthy", pt: "Saudável" },
  { en: "Unhealthy", pt: "Não saudável" },
  { en: "Ham", pt: "Presunto" },
  { en: "What", pt: "O que" },
  { en: "Where", pt: "Onde" },
  { en: "When", pt: "Quando" },
  { en: "Why", pt: "Por que" },
  { en: "Cold", pt: "Frio" }
]);
