QuizCore.createGame([
    {"en": "To break the news", "pt": "Dar a má notícia"},
    {"en": "To spill the beans", "pt": "Falar demais"},
    {"en": "To keep it together", "pt": "Manter a compostura"}, 
    {"en": "It is believed", "pt": "Acredita-se que"}, 
    {"en": "The odd one out", "pt": "O diferente"}, 
    {"en": "Is thought to be", "pt": "Pensa-se que é"}, 
    {"en": "To fit like a glove", "pt": "Cair como uma luva"}, 
    {"en": "To catch an eye", "pt": "Chamar a atenção"}, 
    {"en": "Put yourself in someone's shoes", "pt": "Coloque-se no lugar de alguém"}, 
    {"en": "Time and tide wait for no man", "pt": "O tempo não para"}, 
    {"en": "A chip off the old block", "pt": "Filho de peixe, peixinho é"}, 
    {"en": "The early bird catches the worm", "pt": "Deus ajuda quem cedo madruga"}, 
    {"en": "Once upon a time", "pt": "Era uma vez"}, 
    {"en": "Too many cooks spoil the broth", "pt": "Muitos chefes na cozinha estragam a comida"}, 
    {"en": "A friend in need is a friend indeed", "pt": "Amigo na necessidade é amigo mesmo"}, 
    {"en": "To mess up big time", "pt": "Estragar tudo"},
    {"en": "Don't count your chickens before they're hatched", "pt": "Não conte com os ovos antes de eclodirem"},
    {"en": "To be out of yourself", "pt": "Estar fora de si"}, 
    {"en": "By far", "pt": "De longe"}, 
    {"en": "Every cloud has a silver lining", "pt": "Há males que vêm para o bem"}, 
    {"en": "Out of my element", "pt": "Deslocado"}, 
    {"en": "To stay in the spotlight", "pt": "Manter-se  em alta"}, 
    {"en": "To buckle down", "pt": "Colocar as mãos à obra"}, 
    {"en": "To get rid of", "pt": "Livrar-se"}, 
    {"en": "To give credit where credit is due", "pt": "Dar mérito a quem merece"}, 
    {"en": "To make ends meet", "pt": "Fazer as contas baterem"}, 
    {"en": "It takes two to tango", "pt": "Quando um nao quer, dois nao brigam"}, 
    {"en": "To hit the box offices", "pt": "Fazer sucesso de bilheteira"}, 
    {"en": "Every dog has its day", "pt": "Todo mundo tem seu dia"}, 
    {"en": "I'd Rather", "pt": "Eu prefiro"},  
    {"en": "As a matter of fact", "pt": "Na verdade"}, 
    {"en": "Get this straight", "pt": "Esclarecer"}, 
    {"en": "Don't judge a book by its cover", "pt": "Julgar um livro pela capa"}, 
    {"en": "What goes around comes around", "pt": "Tudo que vai volta"}, 
    {"en": "In order to", "pt": "A fim de"}, 
    {"en": "To appease the conscience", "pt": "Limpar a consciência"}, 
    {"en": "To be portrayed as", "pt": "Ser retratado como"}, 
    {"en": "To have a stiff upper lip", "pt": "Manter a compostura"}, 
    {"en": "When in Rome do as the romans do", "pt": "Quando em Roma, faça como os romanos"}, 
    {"en": "Prone to", "pt": "Propenso a"},
    {"en": "To bottle up", "pt": "Reprimir"},
    {"en": "Beggars can't be choosers", "pt": "Quem não tem escolha não pode ser exigente"}, 
    {"en": "To burst with curiosity", "pt": "Estar cheio de curiosidade"}, 
    {"en": "To burst into tears", "pt": "Cair em lágrimas"}, 
    {"en": "To strike out", "pt": "Repreender"}, 
    {"en": "It has nothing to do with", "pt": "Não tem nada a ver com"}, 
    {"en": "Shed some light", "pt": "Esclarecer"}, 
    {"en": "Hit the jackpot", "pt": "Tirar a sorte grande"}, 
    {"en": "Work like a dog", "pt": "Trabalhar muito"}, 
    {"en": "A bad workman blames his tools", "pt": "Ruim é o carpinteiro quie culpa suas ferramentas"}, 
    {"en": "To run a business", "pt": "Gerir um negócio"}, 
    {"en": "Throw the baby out with the bath water", "pt": "Jogar o bebê fora junto com a água do banho"}, 
    {"en": "To run for", "pt": "Se candidatar"}, 
    {"en": "Pays off", "pt": "Vale a pena"},  
    {"en": "When it comes to", "pt": "Quando se trata de"}, 
    {"en": "Cost an arm and a leg", "pt": "Custar muito "}, 
    {"en": "All work and no play makes Jack a dull boy", "pt": "Só trabalho e nada de diversão faz da vida uma chatice"}, 
    {"en": "As long as", "pt": "Desde que"}, 
    {"en": "To be in tune with", "pt": "Estar em sintonia"}, 
    {"en": "A fool and his money are soon parted", "pt": "Uma pessoa tola perde o dinheiro facilmente"}, 
    {"en": "To rail around", "pt": "Contornar"}, 
    {"en": "To not sleep a wink", "pt": "Não dormir nada"}, 
    {"en": "You can't teach an old dog new tricks", "pt": "Não dá pra ensinar novos truques a um cão velho"}, 
    {"en": "In no time", "pt": "Rápido"},
    {"en": "Feel like a million dollars", "pt": "Sentir-se muito bem"},
    {"en": "A bird in the hand is worth two in the bush", "pt": "Melhor um na mão do que dois voando"}, 
    {"en": "To be up to", "pt": "Tramar"}, 
    {"en": "It's no use crying over split milk", "pt": "Não adianta chorar pelo leite derramado."}, 
    {"en": "Burn the midnight oil", "pt": "Ficar acordado até tarde"}, 
    {"en": "Rome was not built in one day", "pt": "Roma não foi construída em um dia"}]);  