QuizCore.createGame([
    {"en": "To blame", "pt": "Culpar"}, 
    {"en": "To display", "pt": "Exibir"}, 
    {"en": "To adress", "pt": "Endereçar"}, 
    {"en": "To crave", "pt": "Desejar"}, 
    {"en": "To stress", "pt": "Estressar"}, 
    {"en": "To dress up", "pt": "Vestir-se"}, 
    {"en": "To stare", "pt": "Encarar"}, 
    {"en": "To glance", "pt": "Olhar rapidamente"}, 
    {"en": "To appear", "pt": "Aparecer"}, 
    {"en": "To rule", "pt": "Governar"}, 
    {"en": "To undergo", "pt": "Passar por"}, 
    {"en": "To chop", "pt": "Picar"}, 
    {"en": "To stir", "pt": "Mexer"}, 
    {"en": "To toss", "pt": "Arremessar"}, 
    {"en": "To stir-fry", "pt": "Refogar"}, 
    {"en": "To skimp on", "pt": "Economizar"}, 
    {"en": "To mince", "pt": "Moiar"}, 
    {"en": "To bother", "pt": "Incomodar"}, 
    {"en": "To harass", "pt": "Assediar"}, 
    {"en": "To pester", "pt": "Importunar"}, 
    {"en": "To declare", "pt": "Declarar"}, 
    {"en": "To stand by ", "pt": "Defender"}, 
    {"en": "To proclaim", "pt": "Proclamar"}, 
    {"en": "To jeer", "pt": "Vaiar"}, 
    {"en": "To glow ", "pt": "Brilhar"}, 
    {"en": "To flash", "pt": "Piscar"},  
    {"en": "To regret ", "pt": "Arrepender-se"}, 
    {"en": "To go on", "pt": "Continuar"}, 
    {"en": "To bequeath", "pt": "Legar"}, 
    {"en": "To poll", "pt": "Sondar"}, 
    {"en": "To evade", "pt": "Evitar"}, 
    {"en": "To convey", "pt": "Transmitir"}, 
    {"en": "To neglect", "pt": "Negligenciar"}, 
    {"en": "To snap", "pt": "Quebrar"}, 
    {"en": "To rot", "pt": "Apodrecer"}, 
    {"en": "To crush", "pt": "Esmagar"}, 
    {"en": "To strugle", "pt": "ter dificuldade"}, 
    {"en": "To skyrocket", "pt": "Disparar"}, 
    {"en": "To drop", "pt": "Largar"}, 
    {"en": "To influence", "pt": "Influenciar"}, 
    {"en": "To sway", "pt": "Balançar"}, 
    {"en": "To affect", "pt": "Afetar"}, 
    {"en": "To think through", "pt": "Refletir"}, 
    {"en": "To attain", "pt": "Alcançar"}, 
    {"en": "To achieve", "pt": "Conseguir"}, 
    {"en": "To reach", "pt": "Alcançar"}, 
    {"en": "To fix", "pt": "Consertar"}, 
    {"en": "To renovate", "pt": "Renovar"}, 
    {"en": "To be in charge of", "pt": "Encarregado de"}, 
    {"en": "To pamper", "pt": "Paparicar"}, 
    {"en": "To cater to", "pt": "Atender às necessidades"}, 
    {"en": "To protect", "pt": "Proteger"}, 
    {"en": "To handle", "pt": "Lidar"}, 
    {"en": "To Overwhelm", "pt": "Sobrecarregar"}, 
    {"en": "To set free", "pt": "Libertar"}, 
    {"en": "To cope with", "pt": "Lidar"}]);