QuizCore.createGame([
  {en: "By and large", pt: "De modo geral"},
  {en: "Against all odds", pt: "Contra todas as probabilidades"},
  {en: "At the expense of", pt: "À custa de"},
  {en: "In the long run", pt: "A longo prazo"},
  {en: "To leave no stone unturned", pt: "Não deixar pedra sobre pedra"},
  {en: "Far-fetched", pt: "Pouco crível"},
  {en: "To be on the verge of", pt: "Estar prestes a"},
  {en: "To play devil's advocate", pt: "Advogar o contrário"},
  {en: "It goes without saying", pt: "É óbvio"},
  {en: "To weigh the pros and cons", pt: "Pesar os prós e contras"},
  {en: "In hindsight", pt: "Em retrospecto"},
  {en: "To push the envelope", pt: "Ir além dos limites"},
  {en: "On the brink of", pt: "À beira de"},
  {en: "Under no circumstances", pt: "Sob nenhuma circunstância"},
  {en: "All things considered", pt: "Tudo considerado"},
  {en: "By no means", pt: "De forma alguma"},
  {en: "To draw a fine line", pt: "Fazer uma distinção sutil"},
  {en: "At face value", pt: "Ao pé da letra"},
  {en: "To make matters worse", pt: "Para piorar a situação"},
  {en: "In light of", pt: "À luz de"},
  {en: "To stand one's ground", pt: "Manter sua posição"},
  {en: "In a nutshell", pt: "Resumidamente"},
  {en: "On second thought", pt: "Pensando melhor"},
  {en: "To call something into question", pt: "Colocar algo em dúvida"},
  {en: "As a rule of thumb", pt: "Como regra geral"},
  {en: "To take something with a grain of salt", pt: "Levar com cautela"},
  {en: "For the sake of", pt: "Em nome de"},
  {en: "To hold something against someone", pt: "Guardar ressentimento"},
  {en: "In the heat of the moment", pt: "No calor do momento"},
  {en: "To the best of my knowledge", pt: "Até onde sei"},
  {en: "On the grounds that", pt: "Com base no fato de que"},
  {en: "To say the least", pt: "Para dizer o mínimo"},
  {en: "To bring something to light", pt: "Trazer algo à tona"},
  {en: "In due course", pt: "No devido tempo"},
  {en: "At odds with", pt: "Em desacordo com"},
  {en: "In the aftermath of", pt: "Após / na sequência de"},
  {en: "To rule something out", pt: "Descartar algo"},
  {en: "All the more so", pt: "Ainda mais"},
  {en: "To a certain extent", pt: "Até certo ponto"},
  {en: "Give it a whirl", pt: "Experimentar"},
  {en: "Neither fish nor fowl", pt: "Não é uma coisa nem outra"},
  {en: "It's plain as day", pt: "Está na cara."},
  {en: "The tip of the iceberg", pt: "A ponta do iceberg"},
  {en: "Threw in the towel", pt: "Desistir"},
  {en: "Gone out the window", pt: "Foi por água abaixo"},
  {en: "Stand a little taller", pt: "Sentir-se mais confiante"},
  {en: "I am all ears", pt: "Sou todo ouvidos"},
  {en: "Get my head around", pt: "Compreender"},
  {en: "Floating around", pt: "Circulando por aí"},
  {en: "Breaking the law", pt: "Violar a lei"},
  {en: "Hold my breath", pt: "Prender a respiração"},
  {en: "Put our heads together", pt: "Juntar as cabeças"},
  {en: "Walk in someone's shoes", pt: "Colocar-se no lugar dele"},
  {en: "Beating the odds", pt: "Superar as adversidades"},
  {en: "The flip side of the coin", pt: "O outro lado da moeda"},
  {en: "Give me a heads-up about", pt: "Me avise sobre"},
  {en: "Turn of the tide", pt: "Mudança de rumo"},
  {en: "Given rise to", pt: "Deu origem a"},
  {en: "Put my heart and soul into", pt: "Dediquei-me de corpo e alma a isso."},
  {en: "In two minds", pt: "Indeciso"},
  {en: "Cutting-edge", pt: "De ponta"},
  {en: "Move with the times", pt: "Acompanhar os tempos"},
  {en: "Lives up to the hype", pt: "Corresponde às expectativas"},
  {en: "Guinea pig", pt: "Cobaia"},
  {en: "Pave the way for", pt: "Abrir caminho para"},
  {en: "Get down to business", pt: "Ir direto ao assunto"},
  {en: "Be down-to-earth", pt: "Ter os pés no chão"},
  {en: "Keep your eye on the ball", pt: "Mantenha o foco no objetivo"},
  {en: "A safe bet", pt: "Uma aposta segura"},
  {en: "Twist my arm", pt: "Me convencer"},
  {en: "Take the bull by the horns", pt: "Enfrentar o problema de frente"},
  {en: "The world was her oyster", pt: "O mundo estava aos seus pés"},
  {en: "Is not my jam", pt: "Não é muito a minha praia"},
  {en: "Off-the-books", pt: "Não declarado"},
  {en: "Hit the nail on the head", pt: "Acertar em cheio"},
  {en: "The apple of my eye", pt: "Meu xodó"},
  {en:"Steal someone's thunder", pt:"Roubar a cena"},
  {en: "Dive deeper", pt: "Aprofunde-se"},
  {en: "Finding a needle in a haystack", pt: "Achar uma agulha no palheiro"},
  {en: "Lost my touch", pt: "Perdi o jeito"},
  {en: "Got hooked on", pt: "Ficou viciado em"},
  {en: "Break new ground", pt: "Abriu novos caminhos para"},
  {en: "Pulling strings", pt: "Mexer os pauzinhos"},
  {en: "A big fish in a small pond", pt: "Um peixe grande num aquário pequeno"},
  {en: "A bed of roses", pt: "Um mar de rosas"},
  {en: "Runs in our blood", pt: "Está no nosso sangue"},
  {en: "Elephant in the room", pt: "O elefante na sala"},
  {en: "I know which side my bread is buttered on", pt: "Eu sei onde o meu calo aperta"},
  {en: "At zero hour", pt: "Na hora H"},
  {en: "Bits and pieces", pt: "Fragmentos e retalhos"},
  {en: "Tempest in a teapot", pt: "Tempestade em copo d'água"},
  {en: "Beyond a shadow of a doubt", pt: "Sem sombra de dúvida"},
  {en: "To read between the lines", pt: "Ler nas entrelinhas"},
  {en: "To cut corners", pt: "Fazer algo de qualquer jeito"},
  {en: "To bend over backwards", pt: "Fazer de tudo para ajudar"},
  {en: "The ball is in your court", pt: "A decisão é sua"},
  {en: "To let the cat out of the bag", pt: "Revelar um segredo"},
  {en: "To get cold feet", pt: "Amarelar"},
  {en: "To be on the same page", pt: "Estar em sintonia"},
  {en: "To weather the storm", pt: "Superar tempos difíceis"}]);