QuizCore.createGame([
  { en: "By and large", pt: "De modo geral" },
  { en: "Against all odds", pt: "Contra todas as probabilidades" },
  { en: "At the expense of", pt: "À custa de" },
  { en: "In the long run", pt: "A longo prazo" },
  { en: "To leave no stone unturned", pt: "Não deixar pedra sobre pedra" },
  { en: "Far-fetched", pt: "Pouco crível" },
  { en: "To be on the verge of", pt: "Estar prestes a" },
  { en: "To play devil's advocate", pt: "Advogar o contrário" },
  { en: "It goes without saying", pt: "É óbvio" },
  { en: "To weigh the pros and cons", pt: "Pesar os prós e contras" },
  { en: "In hindsight", pt: "Em retrospecto" },
  { en: "To push the envelope", pt: "Ir além dos limites" },
  { en: "On the brink of", pt: "À beira de" },
  { en: "Under no circumstances", pt: "Sob nenhuma circunstância" },
  { en: "All things considered", pt: "Tudo considerado" },
  { en: "By no means", pt: "De forma alguma" },
  { en: "To draw a fine line", pt: "Fazer uma distinção sutil" },
  { en: "At face value", pt: "Ao pé da letra" },
  { en: "To make matters worse", pt: "Para piorar a situação" },
  { en: "In light of", pt: "À luz de" },
  { en: "To stand one's ground", pt: "Manter sua posição" },
  { en: "In a nutshell", pt: "Resumidamente" },
  { en: "On second thought", pt: "Pensando melhor" },
  { en: "To call something into question", pt: "Colocar algo em dúvida" },
  { en: "As a rule of thumb", pt: "Como regra geral" },
  { en: "To take something with a grain of salt", pt: "Levar com cautela" },
  { en: "For the sake of", pt: "Em nome de" },
  { en: "To hold something against someone", pt: "Guardar ressentimento" },
  { en: "In the heat of the moment", pt: "No calor do momento" },
  { en: "To the best of my knowledge", pt: "Até onde sei" },
  { en: "On the grounds that", pt: "Com base no fato de que" },
  { en: "To say the least", pt: "Para dizer o mínimo" },
  { en: "To bring something to light", pt: "Trazer algo à tona" },
  { en: "In due course", pt: "No devido tempo" },
  { en: "To make ends meet", pt: "Fechar as contas" },
  { en: "At odds with", pt: "Em desacordo com" },
  { en: "In the aftermath of", pt: "Após / na sequência de" },
  { en: "To rule something out", pt: "Descartar algo" },
  { en: "All the more so", pt: "Ainda mais" },
  { en: "To a certain extent", pt: "Até certo ponto" }
]);