QuizCore.createGame([
  { en: "To vindicate", pt: "Inocentar / justificar" },
  { en: "To exacerbate", pt: "Agravar" },
  { en: "To undermine", pt: "Minar" },
  { en: "To substantiate", pt: "Comprovar" },
  { en: "To forgo", pt: "Abrir mão de" },
  { en: "To rectify", pt: "Corrigir" },
  { en: "To alleviate", pt: "Amenizar" },
  { en: "To anticipate", pt: "Antecipar" },
  { en: "To assert", pt: "Afirmar" },
  { en: "To comply", pt: "Cumprir" },
  { en: "To deduce", pt: "Deduzir" },
  { en: "To foster", pt: "Promover" },
  { en: "To restrain", pt: "Conter" },
  { en: "To refute", pt: "Refutar" },
  { en: "To entail", pt: "Implicar" },
  { en: "To relinquish", pt: "Renunciar / abrir mão" },
  { en: "To circumvent", pt: "Contornar / driblar" },
  { en: "To corroborate", pt: "Corroborar" },
  { en: "To mitigate", pt: "Mitigar" },
  { en: "To ascertain", pt: "Determinar / averiguar" },
  { en: "To advocate", pt: "Defender (uma ideia)" },
  { en: "To attribute", pt: "Atribuir" },
  { en: "To consolidate", pt: "Consolidar" },
  { en: "To devise", pt: "Elaborar / arquitetar" },
  { en: "To elicit", pt: "Provocar / obter" },
  { en: "To forfeit", pt: "Perder / renunciar" },
  { en: "To hamper", pt: "Prejudicar / dificultar" },
  { en: "To implement", pt: "Implementar" },
  { en: "To infer", pt: "Inferir" },
  { en: "To justify", pt: "Justificar" },
  { en: "To leverage", pt: "Alavancar" },
  { en: "To overlook", pt: "Ignorar / deixar passar" },
  { en: "To perceive", pt: "Perceber" },
  { en: "To reconcile", pt: "Conciliar" },
  { en: "To reinforce", pt: "Reforçar" },
  { en: "To scrutinize", pt: "Examinar minuciosamente" },
  { en: "To suspend", pt: "Suspender" },
  { en: "To validate", pt: "Validar" },
  { en: "To withdraw", pt: "Retirar-se / sacar" },
  { en: "To yield", pt: "Produzir / ceder" }
]);
