QuizCore.createGame([
  {en: "To vindicate", pt: "Inocentar, justificar"},
  {en: "To exacerbate", pt: "Agravar"},
  {en: "To undermine", pt: "Minar"},
  {en: "To substantiate", pt: "Comprovar"},
  {en: "To forgo", pt: "Abrir mão de"},
  {en: "To rectify", pt: "Corrigir"},
  {en: "To alleviate", pt: "Amenizar"},
  {en: "To anticipate", pt: "Antecipar"},
  {en: "To assert", pt: "Afirmar"},
  {en: "To comply", pt: "Cumprir"},
  {en: "To deduce", pt: "Deduzir"},
  {en: "To foster", pt: "Promover"},
  {en: "To restrain", pt: "Conter"},
  {en: "To refute", pt: "Refutar"},
  {en: "To entail", pt: "Implicar"},
  {en: "To relinquish", pt: "Renunciar, abrir mão"},
  {en: "To circumvent", pt: "Contornar, driblar"},
  {en: "To corroborate", pt: "Corroborar"},
  {en: "To mitigate", pt: "Mitigar"},
  {en: "To ascertain", pt: "Determinar, averiguar"},
  {en: "To advocate", pt: "Defender (uma ideia)"},
  {en: "To attribute", pt: "Atribuir"},
  {en: "To consolidate", pt: "Consolidar"},
  {en: "To devise", pt: "Elaborar, arquitetar"},
  {en: "To elicit", pt: "Provocar, obter"},
  {en: "To forfeit", pt: "Perder, renunciar"},
  {en: "To hamper", pt: "Prejudicar, dificultar"},
  {en: "To implement", pt: "Implementar"},
  {en: "To infer", pt: "Inferir"},
  {en: "To justify", pt: "Justificar"},
  {en: "To leverage", pt: "Alavancar"},
  {en: "To overlook", pt: "Ignorar, deixar passar"},
  {en: "To perceive", pt: "Perceber"},
  {en: "To reconcile", pt: "Conciliar"},
  {en: "To reinforce", pt: "Reforçar"},
  {en: "To scrutinize", pt: "Examinar minuciosamente"},
  {en: "To suspend", pt: "Suspender"},
  {en: "To validate", pt: "Validar"},
  {en: "To withdraw", pt: "Retirar-se, sacar"},
  {en: "To yield", pt: "Produzir, ceder"},
  {en: "To misplace", pt: "Perder, colocar no lugar errado"},
  {en: "To condemn", pt: "Condenar"},
  {en: "To blend", pt: "Misturar"},
  {en: "To criticize", pt: "Criticar"},
  {en: "To disregard", pt: "Desconsiderar"},
  {en: "To interact", pt: "Interagir"},
  {en: "To liberate", pt: "Libertar"},
  {en: "To intend", pt: "Pretender"},
  {en: "To advertise", pt: "Anunciar"},
  {en: "To depict", pt: "Retratar"},
  {en: "To reject", pt: "Rejeitar"},
  {en: "To contemplate", pt: "Contemplar, considerar"},
  {en: "To disrupt", pt: "Interromper, causar ruptura"},
  {en: "To stream", pt: "Transmitir"},
  {en: "To surge", pt: "Disparar, aumentar rapidamente"},
  {en: "To strengthen", pt: "Fortalecer"},
  {en: "To permeate", pt: "Permear"},
  {en: "To resonate", pt: "Ressoar, repercutir"},
  {en: "To shift", pt: "Mudar, deslocar"},
  {en: "To diminish", pt: "Diminuir"},
  {en: "To react", pt: "Reagir"},
  {en: "To recap", pt: "Recapitular"},
  {en: "To underestimate", pt: "Subestimar"},
  {en: "To finance", pt: "Financiar"},
  {en: "To thrive", pt: "Prosperar"},
  {en: "To employ", pt: "Empregar"},
  {en: "To recall", pt: "Recordar"},
  {en: "To confront", pt: "Confrontar"},
  {en: "To provide", pt: "Fornecer"},
  {en: "To evolve", pt: "Evoluir"},
  {en: "To eliminate", pt: "Eliminar"},
  {en: "To prove", pt: "Comprovar"},
  {en: "To estimate", pt: "Estimar"},
  {en: "To highlight", pt: "Destacar"},
  {en: "To label", pt: "Rotular"},
  {en: "To overcome", pt: "Superar"},
  {en: "To equip", pt: "Equipar"},
  {en: "To inhibit", pt: "Inibir"},
  {en: "To assume", pt: "Pressupor, assumir"},
  {en: "To rebel", pt: "Rebelar-se"},
  {en: "To comprise", pt: "Compreender, ser composto por"},
  {en: "To stumble", pt: "Tropeçar"},
  {en: "To anchor", pt: "Ancorar"},
  {en: "To embrace", pt: "Abraçar, adotar"},
  {en: "To reclaim", pt: "Recuperar, reivindicar"},
  {en: "To vow", pt: "Jurar"},
  {en: "To urge", pt: "Instar, incentivar"},
  {en: "To exist", pt: "Existir"},
  {en: "To host", pt: "Hospedar, sediar"},
  {en: "To judge", pt: "Julgar"},
  {en: "To obfuscate", pt: "Obscurecer, dificultar a compreensão"},
  {en: "To articulate", pt: "Articular, expressar claramente"},
  {en: "To disclose", pt: "Divulgar, revelar"},
  {en: "To distort", pt: "Distorcer"},
  {en: "To exemplify", pt: "Exemplificar"},
  {en: "To expedite", pt: "Acelerar"},
  {en: "To formulate", pt: "Formular"},
  {en: "To prescribe", pt: "Prescrever"},
  {en: "To render", pt: "Tornar, prestar"},
  {en: "To withstand", pt: "Resistir, suportar"}]);