QuizCore.createGame([
  {en: "Wistful", pt: "Melancólico, nostálgico"},
  {en: "Shrewd", pt: "Astuto, sagaz"},
  {en: "Tepid", pt: "Morno, indiferente"},
  {en: "Bewildered", pt: "Perplexo, confuso"},
  {en: "Brash", pt: "Impulsivo, arrogante"},
  {en: "Devious", pt: "Desonesto, ardiloso"},
  {en: "Aloof", pt: "Distante, reservado"},
  {en: "Fickle", pt: "Inconstante, volúvel"},
  {en: "Frugal", pt: "Econômico, moderado"},
  {en: "Grim", pt: "Sombrio, severo"},
  {en: "Hapless", pt: "Infeliz, azarado"},
  {en: "Hefty", pt: "Pesado, robusto"},
  {en: "Meager", pt: "Escasso, insuficiente"},
  {en: "Moot", pt: "Irrelevante, discutível"},
  {en: "Nimble", pt: "Ágil, rápido"},
  {en: "Petty", pt: "Mesquinho"},
  {en: "Rugged", pt: "Resistente, rude"},
  {en: "Stern", pt: "Severo, rígido"},
  {en: "Tedious", pt: "Entediante, cansativo"},
  {en: "Terse", pt: "Conciso, seco"},
  {en: "Vivid", pt: "Vívido, claro"},
  {en: "Wary", pt: "Cauteloso, desconfiado"},
  {en: "Weary", pt: "Cansado, fatigado"},
  {en: "Adamant", pt: "Inflexível, firme"},
  {en: "Candid", pt: "Honesto, franco"},
  {en: "Barren", pt: "Estéril, improdutivo"},
  {en: "Decrepit", pt: "Decrépito, gasto"},
  {en: "Feeble", pt: "Fraco, debilitado"},
  {en: "Lukewarm", pt: "Morno, indiferente"},
  {en: "Mirthful", pt: "Alegre, divertido"},
  {en: "Prone", pt: "Propenso, suscetível"},
  {en: "Ruthless", pt: "Implacável, cruel"},
  {en: "Sly", pt: "Astuto, ardiloso"},
  {en: "Tangible", pt: "Concreto, perceptível"},
  {en: "Vague", pt: "Vago, indefinido"},
  {en: "Wretched", pt: "Miserável, deplorável"},
  {en: "Gloomy", pt: "Sombrio, desanimado"},
  {en: "Brisk", pt: "Rápido, enérgico"},
  {en: "Cumbersome", pt: "Pesado, difícil de manejar"},
  {en: "Erratic", pt: "Impulsivo, imprevisível"},
  {en: "Dismal", pt: "Triste, lamentável"},
  {en: "Norm", pt: "Norma"},
  {en: "Perspective", pt: "Perspectiva"},
  {en: "Multiculturalism", pt: "Multiculturalismo"},
  {en: "Recognition", pt: "Reconhecimento"},
  {en: "Diffusion", pt: "Difusão"},
  {en: "Inequality", pt: "Desigualdade"},
  {en: "Globalization", pt: "Globalização"},
  {en: "Ancestor", pt: "Ancestral"},
  {en: "Conflict", pt: "Conflito"},
  {en: "Contribution", pt: "Contribuição"},
  {en: "Heritage", pt: "Patrimônio, herança cultural"},
  {en: "Extinct", pt: "Extinto"},
  {en: "Indigenous", pt: "Indígena"},
  {en: "Existence", pt: "Existência"},
  {en: "Migration", pt: "Migração"},
  {en: "Delicate", pt: "Delicado"},
  {en: "Distinct", pt: "Distinto"},
  {en: "Pride", pt: "Orgulho"},
  {en: "Discrimination", pt: "Discriminação"},
  {en: "Concept", pt: "Conceito"},
  {en: "Reluctant", pt: "Relutante"},
  {en: "Dilemma", pt: "Dilema"},
  {en: "Enslaved", pt: "Escravizado"},
  {en: "Intertwined", pt: "Entrelaçado"},
  {en: "Undesirable", pt: "Indesejável"},
  {en: "Spotlight", pt: "Destaque"},
  {en: "Virtue", pt: "Virtude"},
  {en: "Dynasty", pt: "Dinastia"},
  {en: "Lilting", pt: "Cadenciado, melodioso"},
  {en: "Affectionate", pt: "Afetuoso"},
  {en: "Off-balance", pt: "Desequilibrado"},
  {en: "Beloved", pt: "Muito amado"},
  {en: "Conviction", pt: "Convicção"},
  {en: "Exclusivity", pt: "Exclusividade"},
  {en: "Appreciation", pt: "Apreciação"},
  {en: "Hatred", pt: "Ódio"},
  {en: "Noble", pt: "Nobre"},
  {en: "Idealistic", pt: "Idealista"},
  {en: "Spectrum", pt: "Espectro"},
  {en: "Segregation", pt: "Segregação"},
  {en: "Asset", pt: "Recurso, ativo"},
  {en: "Isolated", pt: "Isolado"},
  {en: "Inappropriate", pt: "Inapropriado"},
  {en: "Cohesive", pt: "Coeso"},
  {en: "Derogatory", pt: "Pejorativo"},
  {en: "Skepticism", pt: "Ceticismo"},
  {en: "Spontaneously", pt: "Espontaneamente"},
  {en: "Framework", pt: "Estrutura conceitual"},
  {en: "Preservation", pt: "Preservação"},
  {en: "Momentum", pt: "Impulso"},
  {en: "Resilience", pt: "Resiliência"},
  {en: "Phenomenon", pt: "Fenômeno"},
  {en: "Groundbreaking", pt: "Inovador"},
  {en: "Unparalleled", pt: "Sem igual"},
  {en: "Integrity", pt: "Integridade"},
  {en: "Accountability", pt: "Responsabilidade, prestação de contas"},
  {en: "Consensus", pt: "Consenso"},
  {en: "Bias", pt: "Viés, parcialidade"},
  {en: "Premise", pt: "Premissa"}]);