QuizCore.createGame([
  { en: "Wistful", pt: "Melancólico / nostálgico" },
  { en: "Shrewd", pt: "Astuto / sagaz" },
  { en: "Tepid", pt: "Morno / indiferente" },
  { en: "Bewildered", pt: "Perplexo / confuso" },
  { en: "Brash", pt: "Impulsivo / arrogante" },
  { en: "Devious", pt: "Desonesto / ardiloso" },
  { en: "Aloof", pt: "Distante / reservado" },
  { en: "Fickle", pt: "Inconstante / volúvel" },
  { en: "Frugal", pt: "Econômico / moderado" },
  { en: "Grim", pt: "Sombrio / severo" },
  { en: "Hapless", pt: "Infeliz / azarado" },
  { en: "Hefty", pt: "Pesado / robusto" },
  { en: "Meager", pt: "Escasso / insuficiente" },
  { en: "Moot", pt: "Irrelevante / discutível" },
  { en: "Nimble", pt: "Ágil / rápido" },
  { en: "Petty", pt: "Mesquinho" },
  { en: "Rugged", pt: "Resistente / rude" },
  { en: "Stern", pt: "Severo / rígido" },
  { en: "Tedious", pt: "Entediante / cansativo" },
  { en: "Terse", pt: "Conciso / seco" },
  { en: "Vivid", pt: "Vívido / claro" },
  { en: "Wary", pt: "Cauteloso / desconfiado" },
  { en: "Weary", pt: "Cansado / fatigado" },
  { en: "Adamant", pt: "Inflexível / firme" },
  { en: "Candid", pt: "Honesto / franco" },
  { en: "Barren", pt: "Estéril / improdutivo" },
  { en: "Decrepit", pt: "Decrépito / gasto" },
  { en: "Feeble", pt: "Fraco / debilitado" },
  { en: "Lukewarm", pt: "Morno / indiferente" },
  { en: "Mirthful", pt: "Alegre / divertido" },
  { en: "Prone", pt: "Propenso / suscetível" },
  { en: "Ruthless", pt: "Implacável / cruel" },
  { en: "Sly", pt: "Astuto / ardiloso" },
  { en: "Tangible", pt: "Concreto / perceptível" },
  { en: "Vague", pt: "Vago / indefinido" },
  { en: "Wretched", pt: "Miserável / deplorável" },
  { en: "Gloomy", pt: "Sombrio / desanimado" },
  { en: "Brisk", pt: "Rápido / enérgico" },
  { en: "Cumbersome", pt: "Pesado / difícil de manejar" },
  { en: "Erratic", pt: "Impulsivo / imprevisível" },
  { en: "Dismal", pt: "Triste / lamentável" }
]);
