QuizCore.createGame([
  { en: "Ubiquitous", pt: "Onipresente" },
  { en: "Meticulous", pt: "Meticuloso" },
  { en: "Unprecedented", pt: "Sem precedentes" },
  { en: "Ambiguous", pt: "Ambíguo" },
  { en: "Resilient", pt: "Resiliente" },
  { en: "Cumbersome", pt: "Difícil de lidar" },
  { en: "Plausible", pt: "Plausível" },
  { en: "Notwithstanding", pt: "Apesar de" },
  { en: "Salient", pt: "Proeminente" },
  { en: "Elusive", pt: "Difícil de alcançar" },
  { en: "Conspicuous", pt: "Chamativo" },
  { en: "Intricate", pt: "Intrincado" },
  { en: "Redundant", pt: "Redundante" },
  { en: "Inherent", pt: "Inerente" },
  { en: "Detrimental", pt: "Prejudicial" },
  { en: "Vigorous", pt: "Vigoroso" },
  { en: "Subtle", pt: "Sutil" },
  { en: "Daunting", pt: "Intimidador" },
  { en: "Pervasive", pt: "Generalizado" },
  { en: "Arbitrary", pt: "Arbitrário" },
  { en: "Feasible", pt: "Viável" },
  { en: "Skeptical", pt: "Cético" },
  { en: "Imminent", pt: "Iminente" },
  { en: "Coherent", pt: "Coerente" },
  { en: "Marginal", pt: "Insignificante / Marginal" },
  { en: "Robust", pt: "Sólido / Robusto" },
  { en: "Tentative", pt: "Provisório" },
  { en: "Pragmatic", pt: "Pragmático" },
  { en: "Compelling", pt: "Convincente" },
  { en: "Contingent", pt: "Condicional" },
  { en: "Negligible", pt: "Desprezível" },
  { en: "Scrutinized", pt: "Examinado minuciosamente" },
  { en: "Viable", pt: "Exequível" },
  { en: "Superfluous", pt: "Supérfluo" },
  { en: "Stringent", pt: "Rigoroso" },
  { en: "Convoluted", pt: "Confuso / Complexo" },
  { en: "Insightful", pt: "Perspicaz" },
  { en: "Definitive", pt: "Definitivo" },
  { en: "Contentious", pt: "Polêmico" },
  { en: "Substantial", pt: "Significativo" }
]);