QuizCore.createGame([
        {"en": "Good morning", "pt": "Bom dia"}, 
        {"en": "Good afternoon", "pt": "Boa tarde"}, 
        {"en": "Good evening", "pt": "Boa noite"}, 
        {"en": "Good night", "pt": "Boa noite"}, 
        {"en": "Hello", "pt": "Olá"}, 
        {"en": "Hi", "pt": "Oi"}, 
        {"en": "Bye", "pt": "Tchau"}, 
        {"en": "Goodbye", "pt": "Adeus"}, 
        {"en": "Thank you", "pt": "Obrigado/Obrigada"}, 
        {"en": "You're welcome", "pt": "De nada"}, 
        {"en": "Please", "pt": "Por favor"}, 
        {"en": "Excuse me", "pt": "Com licença"}, 
        {"en": "I'm sorry", "pt": "Sinto muito"}, 
        {"en": "How are you?", "pt": "Como vai?"}, 
        {"en": "I'm fine", "pt": "Estou bem"}, 
        {"en": "What's your name?", "pt": "Qual é o seu nome?"}, 
        {"en": "My name is...", "pt": "Meu nome é..."}, 
        {"en": "Where are you from?", "pt": "De onde você é?"}, 
        {"en": "I'm from Brazil", "pt": "Eu sou do Brasil"}, 
        {"en": "Nice to meet you", "pt": "Prazer em conhecer"}, 
        {"en": "How old are you?", "pt": "Quantos anos você tem?"}, 
        {"en": "I'm 25 years old", "pt": "Eu tenho 25 anos"}, 
        {"en": "What time is it?", "pt": "Que horas são?"}, 
        {"en": "It's 3 o'clock", "pt": "São 3 horas"}, 
        {"en": "Where is the bathroom?", "pt": "Onde é o banheiro?"}, 
        {"en": "How much does it cost?", "pt": "Quanto custa?"}, 
        {"en": "I don't understand", "pt": "Eu não entendo"}, 
        {"en": "Can you help me?", "pt": "Você pode me ajudar?"}, 
        {"en": "I need help", "pt": "Eu preciso de ajuda"}, 
        {"en": "I'm hungry", "pt": "Eu estou com fome"}, 
        {"en": "I'm thirsty", "pt": "Eu estou com sede"}, 
        {"en": "I'm tired", "pt": "Eu estou cansado"}, 
        {"en": "I'm happy", "pt": "Eu estou feliz"}, 
        {"en": "I'm sad", "pt": "Eu estou triste"}, 
        {"en": "I'm busy", "pt": "Eu estou ocupado"}, 
        {"en": "I'm free", "pt": "Eu estou livre"}, 
        {"en": "I'm lost", "pt": "Eu estou perdido"}, 
        {"en": "What's this?", "pt": "O que é isto?"}, 
        {"en": "This is a book", "pt": "Isto é um livro"}, 
        {"en": "I like it", "pt": "Eu gosto disso"}, 
        {"en": "I don't like it", "pt": "Eu não gosto disso"}, 
        {"en": "I love you", "pt": "Eu te amo"}, 
        {"en": "See you later", "pt": "Até logo"}, 
        {"en": "See you tomorrow", "pt": "Até amanhã"}, 
        {"en": "Have a good day", "pt": "Tenha um bom dia"}, 
        {"en": "Have a good weekend", "pt": "Tenha um bom fim de semana"}, 
        {"en": "Take care", "pt": "Tome cuidado"}, 
        {"en": "Be careful", "pt": "Cuidado"}, 
        {"en": "Good luck", "pt": "Boa sorte"}, 
        {"en": "Congratulations", "pt": "Parabéns"}, 
        {"en": "Happy birthday", "pt": "Feliz aniversário"}, 
        {"en": "Merry Christmas", "pt": "Feliz Natal"}, 
        {"en": "Happy New Year", "pt": "Feliz Ano Novo"}, 
        {"en": "Bless you", "pt": "Saúde"}, 
        {"en": "Cheers", "pt": "Saúde/Tim-tim"}, 
        {"en": "Let's go", "pt": "Vamos"}, 
        {"en": "Come here", "pt": "Venha aqui"}, 
        {"en": "Sit down", "pt": "Sente-se"}, 
        {"en": "Stand up", "pt": "Levante-se"}, 
        {"en": "Be quiet", "pt": "Fique quieto"}, 
        {"en": "Speak louder", "pt": "Fale mais alto"}, 
        {"en": "Repeat please", "pt": "Repita por favor"}, 
        {"en": "Slow down", "pt": "Devagar"}, 
        {"en": "Hurry up", "pt": "Apresse-se"}, 
        {"en": "Wait a moment", "pt": "Espere um momento"}, 
        {"en": "I agree", "pt": "Eu concordo"}, 
        {"en": "I disagree", "pt": "Eu discordo"}, 
        {"en": "Maybe", "pt": "Talvez"}, 
        {"en": "Of course", "pt": "Claro"}, 
        {"en": "No problem", "pt": "Sem problemas"}, 
        {"en": "Don't worry", "pt": "Não se preocupe"}, 
        {"en": "It's okay", "pt": "Está tudo bem"}, 
        {"en": "That's right", "pt": "Isso mesmo"}, 
        {"en": "That's wrong", "pt": "Isso está errado"}, 
        {"en": "Are you sure?", "pt": "Você tem certeza?"}, 
        {"en": "I'm sure", "pt": "Eu tenho certeza"}, 
        {"en": "I'm not sure", "pt": "Eu não tenho certeza"}, 
        {"en": "What happened?", "pt": "O que aconteceu?"}, 
        {"en": "Everything is fine", "pt": "Tudo está bem"}, 
        {"en": "What's the matter?", "pt": "O que houve?"}, 
        {"en": "Never mind", "pt": "Deixa pra lá"}, 
        {"en": "I forgot", "pt": "Eu esqueci"}, 
        {"en": "I remember", "pt": "Eu me lembro"}, 
        {"en": "I promise", "pt": "Eu prometo"}, 
        {"en": "Really?", "pt": "Sério?"}, 
        {"en": "Of course not", "pt": "Claro que não"}, 
        {"en": "Why not?", "pt": "Por que não?"}, 
        {"en": "I don't know", "pt": "Eu não sei"}, 
        {"en": "I have no idea", "pt": "Eu não tenho ideia"}, 
        {"en": "Let me think", "pt": "Deixe-me pensar"}, 
        {"en": "I guess so", "pt": "Acho que sim"}, 
        {"en": "I don't think so", "pt": "Acho que não"}, 
        {"en": "Are you kidding?", "pt": "Você está brincando?"}, 
        {"en": "No way!", "pt": "De jeito nenhum!"}, 
        {"en": "Are you serious?", "pt": "Você está falando sério?"}, 
        {"en": "I'm just kidding", "pt": "Estou só brincando"}, 
        {"en": "That's funny", "pt": "Isso é engraçado"}, 
        {"en": "That's not funny", "pt": "Isso não é engraçado"}, 
        {"en": "I'm joking", "pt": "Estou brincando"}, 
        {"en": "You're right", "pt": "Você está certo"}, 
        {"en": "You're wrong", "pt": "Você está errado"}, 
        {"en": "I was wrong", "pt": "Eu estava errado"}, 
        {"en": "My mistake", "pt": "Meu erro"}]);
