QuizCore.createGame([
    {"en": "To blame", "pt": "Culpar"}, 
    {"en": "To display", "pt": "Exibir"}, 
    {"en": "To address", "pt": "Endereçar"}, 
    {"en": "To crave", "pt": "Desejar intensamente"}, 
    {"en": "To stress", "pt": "Estressar, enfatizar"}, 
    {"en": "To dress up", "pt": "Vestir-se"}, 
    {"en": "To stare", "pt": "Encarar"}, 
    {"en": "To glance", "pt": "Olhar rapidamente"}, 
    {"en": "To appear", "pt": "Aparecer"}, 
    {"en": "To rule", "pt": "Governar"}, 
    {"en": "To undergo", "pt": "Passar por"}, 
    {"en": "To chop", "pt": "Picar"}, 
    {"en": "To stir", "pt": "Mexer"}, 
    {"en": "To toss", "pt": "Arremessar"}, 
    {"en": "To stir-fry", "pt": "Refogar"}, 
    {"en": "To skimp on", "pt": "Economizar"}, 
    {"en": "To mince", "pt": "Moer bem, picar"},
    {"en": "To bother", "pt": "Incomodar"}, 
    {"en": "To harass", "pt": "Assediar"}, 
    {"en": "To pester", "pt": "Importunar"}, 
    {"en": "To declare", "pt": "Declarar"}, 
    {"en": "To stand by", "pt": "Apoiar, defender"}, 
    {"en": "To proclaim", "pt": "Proclamar"}, 
    {"en": "To jeer", "pt": "Vaiar"}, 
    {"en": "To glow", "pt": "Brilhar"}, 
    {"en": "To flash", "pt": "Piscar"},  
    {"en": "To regret", "pt": "Arrepender-se"}, 
    {"en": "To go on", "pt": "Continuar"}, 
    {"en": "To bequeath", "pt": "Legar"}, 
    {"en": "To poll", "pt": "Sondar"}, 
    {"en": "To evade", "pt": "Evitar, escapar de"}, 
    {"en": "To convey", "pt": "Transmitir"}, 
    {"en": "To neglect", "pt": "Negligenciar"}, 
    {"en": "To snap", "pt": "Quebrar"}, 
    {"en": "To rot", "pt": "Apodrecer"}, 
    {"en": "To crush", "pt": "Esmagar"}, 
    {"en": "To struggle", "pt": "Ter dificuldade"},
    {"en": "To skyrocket", "pt": "Disparar"}, 
    {"en": "To drop", "pt": "Largar"}, 
    {"en": "To influence", "pt": "Influenciar"}, 
    {"en": "To sway", "pt": "Balançar, influenciar"}, 
    {"en": "To affect", "pt": "Afetar"}, 
    {"en": "To think through", "pt": "Refletir"}, 
    {"en": "To attain", "pt": "Alcançar"}, 
    {"en": "To achieve", "pt": "Conseguir"}, 
    {"en": "To reach", "pt": "Alcançar"}, 
    {"en": "To fix", "pt": "Consertar"}, 
    {"en": "To renovate", "pt": "Renovar"}, 
    {"en": "To be in charge of", "pt": "Encarregado de"}, 
    {"en": "To pamper", "pt": "Paparicar"}, 
    {"en": "To cater to", "pt": "Atender às necessidades"}, 
    {"en": "To protect", "pt": "Proteger"}, 
    {"en": "To handle", "pt": "Lidar"}, 
    {"en": "To overwhelm", "pt": "Sobrecarregar"}, 
    {"en": "To set free", "pt": "Libertar"}, 
    {"en": "To cope with", "pt": "Lidar"},
    {"en": "To stage", "pt": "Encenar"},
    {"en": "To pursue", "pt": "Perseguir"},
    {"en": "To miss", "pt": "Sentir falta de"},
    {"en": "To pick", "pt": "Escolher"},
    {"en": "To cover", "pt": "Cobrir"},
    {"en": "To hurt", "pt": "Machucar"},
    {"en": "To insist", "pt": "Insistir"},
    {"en": "To seek", "pt": "Buscar"},
    {"en": "To convince", "pt": "Convencer"},
    {"en": "To obey", "pt": "Obedecer"},
    {"en": "To engage", "pt": "Envolver, participar"},
    {"en": "To bear", "pt": "Suportar"},
    {"en": "To donate", "pt": "Doar"},
    {"en": "To heal", "pt": "Curar"},
    {"en": "To distinguish", "pt": "Distinguir"},
    {"en": "To promote", "pt": "Promover"},
    {"en": "To empower", "pt": "Capacitar"},
    {"en": "To raise", "pt": "Levantar"},
    {"en": "To enable", "pt": "Habilitar, permitir"},
    {"en": "To educate", "pt": "Educar"},
    {"en": "To reuse", "pt": "Reutilizar"},
    {"en": "To tag", "pt": "Marcar"},
    {"en": "To recycle", "pt": "Reciclar"},
    {"en": "To act", "pt": "Agir"},
    {"en": "To cause", "pt": "Causar"},
    {"en": "To vandalize", "pt": "Vandalizar"},
    {"en": "To crash", "pt": "Colidir"},
    {"en": "To flee", "pt": "Fugir"},
    {"en": "To enhance", "pt": "Aprimorar"},
    {"en": "To own", "pt": "Possuir"},
    {"en": "To launch", "pt": "Lançar"},
    {"en": "To manipulate", "pt": "Manipular"},
    {"en": "To revitalize", "pt": "Revitalizar"},
    {"en": "To remain", "pt": "Permanecer"},
    {"en": "To resist", "pt": "Resistir"},
    {"en": "To train", "pt": "Treinar"},
    {"en": "To invest", "pt": "Investir"},
    {"en": "To balance", "pt": "Equilibrar"},
    {"en": "To ensure", "pt": "Garantir"},
    {"en": "To defeat", "pt": "Derrotar"},
    {"en": "To challenge", "pt": "Desafiar"},
    {"en": "To risk", "pt": "Arriscar"},
    {"en": "To beat", "pt": "Vencer"},
    {"en": "To attract", "pt": "Atrair"}]);