QuizCore.createGame([
        {"en": "Flabbergasted", "pt": "Abismado"}, 
        {"en": "Astonished", "pt": "Espantado"}, 
        {"en": "Indeed", "pt": "De fato"}, 
        {"en": "Background", "pt": "Antecedentes"}, 
        {"en": "Furthermore", "pt": "Além disso"}, 
        {"en": "Role", "pt": "Papel"}, 
        {"en": "Acceptance", "pt": "Aceitação"}, 
        {"en": "Widely", "pt": "Amplamente"}, 
        {"en": "Massive", "pt": "Massivo"}, 
        {"en": "Outfit", "pt": "Traje"}, 
        {"en": "Tide", "pt": "Maré"}, 
        {"en": "Exquisite", "pt": "Exquissito"}, 
        {"en": "Unique", "pt": "Único"}, 
        {"en": "State-of-the-art", "pt": "Mais avançado"}, 
        {"en": "Inedible", "pt": "Incomestível"}, 
        {"en": "Boneless", "pt": "Sem ossos"}, 
        {"en": "Infamy", "pt": "Infâmia"}, 
        {"en": "Commenced", "pt": "Iniciado"}, 
        {"en": "Ambassador", "pt": "Embaixador"}, 
        {"en": "Unbounded", "pt": "Ilimitado"}, 
        {"en": "Dastardly", "pt": "Covarde"}, 
        {"en": "Such", "pt": "Tal"}, 
        {"en": "Addicted", "pt": "Viciado"}, 
        {"en": "Ephemeral", "pt": "Efémero"}, 
        {"en": "Eagerly", "pt": "Ansiosamente"}, 
        {"en": "Stardom", "pt": "Fama"}, 
        {"en": "Second-rate", "pt": "De segunda categoria"}, 
        {"en": "Amazed", "pt": "Maravilhado"}, 
        {"en": "Mocked", "pt": "Ridicularizado"}, 
        {"en": "Worth", "pt": "Valor"}, 
        {"en": "Sparkling", "pt": "Cintilante"}, 
        {"en": "Flop", "pt": "Fiasco"}, 
        {"en": "Balance", "pt": "Equilíbrio"}, 
        {"en": "Twist", "pt": "Reviravolta"}, 
        {"en": "Plot", "pt": "Enredo"}, 
        {"en": "Bounty hunter", "pt": "Caçador de recompensas"}, 
        {"en": "Authentic", "pt": "Autentico"}, 
        {"en": "Hard feelings", "pt": "Ressentimentos"},
        {"en": "Literature", "pt": "Literatura"}, 
        {"en": "Inheritor", "pt": "Herdeiro"}, 
        {"en": "Wealth", "pt": "Riqueza "}, 
        {"en": "Moiety", "pt": "Fração"}, 
        {"en": "Faux pas", "pt": "Gafe"}, 
        {"en": "Filthy", "pt": "Imundo"}, 
        {"en": "Manners", "pt": "Maneiras"}, 
        {"en": "Even though", "pt": "Mesmo que"}, 
        {"en": "Polite", "pt": "Educado"}, 
        {"en": "Politeness", "pt": "Educação"}, 
        {"en": "Border", "pt": "Fronteira"}, 
        {"en": "Margin", "pt": "Margem"}, 
        {"en": "Underlying", "pt": "Implicíto"}, 
        {"en": "Subleties", "pt": "Sutilezas"}, 
        {"en": "Although", "pt": "Embora"}, 
        {"en": "Since", "pt": "Desde"}, 
        {"en": "Grievances", "pt": "Reclamações"}, 
        {"en": "Upbringing", "pt": "Criação"}, 
        {"en": "Assuming that", "pt": "Assumindo que"}, 
        {"en": "Increase", "pt": "Aumento"}, 
        {"en": "High wire", "pt": "Corda bamba"}, 
        {"en": "Perilous", "pt": "Perigoso"}, 
        {"en": "A try out", "pt": "Um teste"}, 
        {"en": "Steep", "pt": "Enorme"}, 
        {"en": "Keep up", "pt": "Acompanhar"}, 
        {"en": "Duty", "pt": "Dever"}, 
        {"en": "Wage", "pt": "Salário"}, 
        {"en": "Masterpiece", "pt": "Obra de arte"}, 
        {"en": "Tuition", "pt": "Propina"}, 
        {"en": "Syllabi", "pt": "Programa de estudos"}, 
        {"en": "Hence", "pt": "Portanto"}, 
        {"en": "Ground rules", "pt": "Regras fundamentais"}, 
        {"en": "Besides", "pt": "Além disso"}, 
        {"en": "One-liners", "pt": "Piada curta"}, 
        {"en": "Endeavor", "pt": "Esforço"}, 
        {"en": "Pampered", "pt": "Paparicado"}, 
        {"en": "Aestheticians", "pt": "Esteticistas"}, 
        {"en": "Utmost", "pt": "Absoluto"}, 
        {"en": "Brand new", "pt": "Novo em folha"}, 
        {"en": "Shielded", "pt": "Protegido"}, 
        {"en": "Target", "pt": "Alvo"}, 
        {"en": "Milestone", "pt": "Marco importante"}, 
        {"en": "Regretfully", "pt": "Infelizmente"}, 
        {"en": "Deadlines", "pt": "Prazos"}, 
        {"en": "Standard", "pt": "Padrão"}, 
        {"en": "Settings", "pt": "Configurações"}, 
        {"en": "Goal", "pt": "Meta"}, 
        {"en": "Attainable", "pt": "Atingível"}, 
        {"en": "Boost", "pt": "Impulso"}, 
        {"en": "Income", "pt": "Rendimento"},
        {"en": "Versatile", "pt": "Versátil"},
        {"en": "Consumerism", "pt": "Consumismo"},
        {"en": "Phony", "pt": "Falso"},
        {"en": "Counterfeit", "pt": "Falso"},
        {"en": "Lifelong search", "pt": "Busca ao longo da vida"},
        {"en": "Subtle", "pt": "Sutil"},
        {"en": "Traits", "pt": "Características"},
        {"en": "Broad", "pt": "Amplo"},
        {"en": "Ever-increasingly", "pt": "Cada vez mais"},
        {"en": "Painstakingly", "pt": "Meticulosamente"}]); 